[package]
name = "rust-irc-server"
version = "0.1.0"
authors = ["Krishna Kumar <krishnak@thoughtworks.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
simple_redis = "0.3.39"
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
